name: Prototype CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: actions/setup-python@v4
        name: Set up Python 3.x
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install scikit-learn jinja2 fire

      - name: Build code index
        run: python scripts/build_code_index.py . data/code_index

      - name: Run prototype pipeline & emit stub
        run: |
          python - << 'EOF'
          import json
          from pipeline.new_feature import run_new_feature
          snippets, stub = run_new_feature("proof-dsl tagless-final example")
          print("=== Snippets ===")
          print(json.dumps(snippets, indent=2))
          with open("ProofDslVerifier.hs", "w") as f:
              f.write(stub)
          print("Wrote stub to ProofDslVerifier.hs")
          EOF
        continue-on-error: true

      - name: Set up GHC
  uses: haskell-actions/setup@v2
  with:
    ghc-version: "9.2.7"

- name: Compile generated stub with ghc
  run: |
    # compile the one Haskell file we generated
    ghc --make ProofDslVerifier.hs -outputdir .build -o prototype-ci

- name: Smoke-test the binary
  run: ./prototype-ci --help || true

