    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install scikit-learn jinja2 fire

      - name: Lint Python
        run: |
          pip install black flake8
          black --check .
          flake8 .

      - name: Run Python tests
        run: |
          pip install pytest
          pytest tests/python

      - name: Build code index
        run: python scripts/build_code_index.py . data/code_index

      # … rest of your steps …

