name: Prototype CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - uses: actions/setup-python@v4
        name: Set up Python 3.x
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install scikit-learn jinja2 fire

      - name: Build code index
        run: python scripts/build_code_index.py . data/code_index

      - name: Run prototype pipeline & emit stub
        run: |
          python - << 'EOF'
          import json
          from pipeline.new_feature import run_new_feature

          snippets, stub = run_new_feature("proof-dsl tagless-final example")

          print("=== Snippets ===")
          print(json.dumps(snippets, indent=2))

          with open("ProofDslVerifier.hs", "w") as f:
              f.write(stub)
          print("Wrote stub to ProofDslVerifier.hs")
          EOF
        continue-on-error: true

      - uses: haskell-actions/setup@v2
        name: Set up GHC (Haskell)
        with:
          ghc-version: "9.2.7"
          cabal-version: "3.6.2.0"

      - name: Build Haskell stub
        run: |
          cabal update
          cabal init --minimal --non-interactive --exe --source-dir=. --dependencies=base
          mkdir -p src
          mv ProofDslVerifier.hs src/Main.hs
          cabal build

      - name: Smoke-test binary
        run: |
          ./dist/build/prototype-ci/prototype-ci --help || true
