name: Prototype CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install scikit-learn jinja2 fire pytest black flake8

      - name: Lint Python
        run: |
          black --check .
          flake8 .

      - name: Run Python tests
        run: |
          python -m pytest tests/python

      - name: Build code index
        run: python scripts/build_code_index.py . data/code_index

      - name: Generate Haskell stub
        continue-on-error: true
        run: |
          python - << 'EOF'
          from pipeline.new_feature import run_new_feature
          _, stub = run_new_feature("proof-dsl tagless-final example")
          with open("ProofDslVerifier.hs", "w") as f:
              f.write(stub)
          print("Stub written")
          EOF

      - name: ✅ Skip Haskell compile (temporary)
        run: echo "Skipping Haskell compile for now"
