name: Prototype CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install scikit-learn jinja2 fire

      - name: Lint Python
        run: |
          pip install black flake8
          black --check .
          flake8 .

      - name: Run Python tests
        run: |
          pip install pytest
          pytest tests/python

      - name: Build code index
        run: python scripts/build_code_index.py . data/code_index

      - name: Run prototype pipeline & emit stub
        continue-on-error: true
        run: |
          python - << 'EOF'
          import json
          from pipeline.new_feature import run_new_feature
          snippets, stub = run_new_feature("proof-dsl tagless-final example")
          print("=== Snippets ===")
          print(json.dumps(snippets, indent=2))
          with open("ProofDslVerifier.hs", "w") as f:
              f.write(stub)
          print("Wrote stub to ProofDslVerifier.hs")
          EOF

      - name: (Temporary) Skip Haskell compile
        run: echo "Skipping Haskell compile for now"
